keys:
  - &admin_ianpascoe age1kmxz23a7s37fn2au7ket7frdnawkenxjwntmf3ff0gdn3ur6s5tseszqsj
  - &server_ians_macbookpro age1769k4fk5ymcs0t8nda6uu3rqhzc7q6up5sxyyascgte2suc9ugss430ne8
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *admin_ianpascoe
          - *server_ians_macbookpro
  - path_regex: secrets/Ians-MacbookPro/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *admin_ianpascoe
          - *server_ians_macbookpro
