#!/usr/bin/env lua

-- Add the sketchybar module to the package cpath
package.cpath = package.cpath .. ";/Users/" .. os.getenv("USER") .. "/.local/share/sketchybar_lua/sketchybar.so"

SketchyBar = require("sketchybar")

SketchyBar.begin_config()
require("bar")
require("default")
require("items")
SketchyBar.hotload(true)
SketchyBar.end_config()

SketchyBar.event_loop()
